# 连接池配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bill-manager
    username: root
    password: root
  thymeleaf:
    cache: false  # 关闭thymeleaf缓存

# 整合mybatis
mybatis:
  type-aliases-package: com.xxy.entity  # 别名搜索
  mapper-locations: classpath:/mapper/*.xml
